x-airflow-common: # definir une configuration commune pour les services Airflow
  &airflow-common
  build: # Construire l'image à partir du Dockerfile
    context: .
    dockerfile: Dockerfile
  env_file:
    - .env
  environment:
  # Utilise l'exécuteur local (pas de Celery/Kubernetes)
    AIRFLOW__CORE__EXECUTOR: LocalExecutor 
  # Connexion à PostgreSQL pour la métabase d'Airflow (historique, DAGs, etc.)
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
  # Clé de chiffrement pour les connexions, laisser vide pour en générer une automatiquement 
    AIRFLOW__CORE__FERNET_KEY: '' 
  # Ne pas charger les DAGs d'exemple      
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
  # Authentification de base pour l'API d'Airflow
    AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth
  # chemin vers le projet dans le conteneur pour que les DAGs puissent l'importer
    YAZAKI_PROJECT_ROOT: /opt/airflow/project 
    PYTHONPATH: /opt/airflow/project
  volumes:
    - ../dags:/opt/airflow/dags
    - ../etl:/opt/airflow/project/etl
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@yazaki.local
      "

  airflow-webserver: # interface utilisateur d'Airflow
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: unless-stopped # Redémarre automatiquement en cas d'erreur ou d'arrêt


  airflow-scheduler: # composant qui planifie et exécute les tâches
    <<: *airflow-common
    command: scheduler
    restart: unless-stopped

volumes:
  postgres-db-volume:
